# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d320ab297c8d4352ef491196a1fcb290e2992b577dac4fbbb6553250d05c52d55074fb56ad0ea4a524a4c13413cde930fefedac0a563ba8a435d855fe497dc52

test:
  secret_key_base: 1b5a69fc3e21e95bb878d4b9ca3b69f7a3a02785be5f9017e3e5a4b94577cb693d2e3ad6bf06a354bfa797c617c92f5d07e1372adc7939ae7f32ea188841a8b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
